spring:
  application:
    name: ClubOS

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: schema.sql

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.codeygen.clubos: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
