package com.codeygen.clubos.entities.audit.enums;

public enum AuditActionType {
    MEMBERS_BULK_IMPORTED,
    MEMBER_PROMOTED_TO_LEAD,
    MEMBER_DEPARTMENT_CHANGED,
    GENERAL_TASK_ASSIGNED,
    OWNERSHIP_TASK_ASSIGNED,
    OWNERSHIP_TASK_DIRECTLY_ASSIGNED,
    TASK_SUBMISSION_REVIEWED,
    TASK_SUBMITTED,
    OWNERSHIP_BID_PLACED,
    OWNERSHIP_BID_UPDATED,
    OWNERSHIP_BIDDING_AUTO_ASSIGNED,
    OWNERSHIP_BIDDING_CLOSED_WITHOUT_VALID_BIDS
}
