create table bid (refunded boolean, tokens_bidded integer, bid_id varchar(255) not null, status varchar(255) check ((status in ('WON','LOST','PENDING'))), task_id varchar(255), user_id varchar(255), primary key (bid_id));
create table department (department_id varchar(255) not null, name varchar(255), user_id varchar(255) unique, primary key (department_id));
create table general_task (task_id varchar(255) not null, primary key (task_id));
create table lead (user_id varchar(255) not null, primary key (user_id));
create table member (cumulative_points integer, tokens_available integer, department_id varchar(255), performance_status varchar(255) check ((performance_status in ('NO_TASKS_ASSIGNED','PASSING','FAILING'))), user_id varchar(255) not null, primary key (user_id));
create table ownership_based_task (number_of_owners integer, bidding_deadline timestamp(6), assignment_status varchar(255) check ((assignment_status in ('BIDDING_OPEN','ASSIGNED_BY_BIDDING','ASSIGNED_BY_LEAD','NO_VALID_BIDS'))), task_id varchar(255) not null, primary key (task_id));
create table panel (user_id varchar(255) not null, primary key (user_id));
create table task (points integer, task_deadline timestamp(6), department_id varchar(255), name varchar(255), task_id varchar(255) not null, task_type varchar(255) check ((task_type in ('GENERAL','OWNERSHIP_BASED'))), primary key (task_id));
create table task_ownership (assigned_points integer, ownership_assigned_at timestamp(6), acquisition_type varchar(255) check ((acquisition_type in ('BID','LEAD_ASSIGNMENT'))), owner_user_id varchar(255), task_id varchar(255), task_ownership_id varchar(255) not null, transferred_to_user_id varchar(255), primary key (task_ownership_id));
create table task_submission (submitted_at timestamp(6), member_id varchar(255), proof_of_submission varchar(255), remarks_by_lead varchar(255), status varchar(255) check ((status in ('SUBMITTED','APPROVED','REJECTED'))), submission_id varchar(255) not null, task_id varchar(255), primary key (submission_id));
create table users (must_change_password boolean, created_at timestamp(6), email varchar(255) unique, name varchar(255), password_hash varchar(255), register_number varchar(255) unique, role varchar(255) check ((role in ('MEMBER','LEAD','PANEL'))), user_id varchar(255) not null, primary key (user_id));
alter table if exists bid add constraint FK1dcdol86bqxqg72q37d7ok4dv foreign key (user_id) references member;
alter table if exists bid add constraint FKsfnysngt47k1pdq00icmpia85 foreign key (task_id) references ownership_based_task;
alter table if exists department add constraint FKj93lescjo1f7rmshlgvw1jmsi foreign key (user_id) references lead;
alter table if exists general_task add constraint FK21y1notngyaqwppdc71rn04qa foreign key (task_id) references task;
alter table if exists lead add constraint FKghqmbdekyynegpxxu918iggt4 foreign key (user_id) references users;
alter table if exists member add constraint FKlmd4h7lh9acdyvi0xxbvsqrmk foreign key (department_id) references department;
alter table if exists member add constraint FKe6yo8tn29so0kdd1mw4qk8tgh foreign key (user_id) references users;
alter table if exists ownership_based_task add constraint FKnryohc7gowj1g5m5ih89ujj29 foreign key (task_id) references task;
alter table if exists panel add constraint FK8ue7dh7huhtdmxdurwkcqx8r3 foreign key (user_id) references users;
alter table if exists task add constraint FKjrbk1sogr5c0l739hw3gg3qdu foreign key (department_id) references department;
alter table if exists task_ownership add constraint FKesx0urbwtr295uxbdg84rqp89 foreign key (owner_user_id) references member;
alter table if exists task_ownership add constraint FK6ctd066ekgmbk1tjknb7o57tl foreign key (transferred_to_user_id) references member;
alter table if exists task_ownership add constraint FKq2od77ew3v4jhggheug7w1xat foreign key (task_id) references ownership_based_task;
alter table if exists task_submission add constraint FK3yaf1hmmqv3x3nm97arynxxqo foreign key (member_id) references member;
alter table if exists task_submission add constraint FKjlw5bs08e3fwrvvtkxnnv24rr foreign key (task_id) references task;
